-- AvKARE commerce: enable the tenant + seed its catalog. Additive + gated to
-- site_key 'avkare'; no other brand is touched. Generated from
-- avkare/drafts/data/avkare-catalog.json. Pairs with 20260819_avkare_theme.sql.

insert into public.brand_configs (site_key, brand_name, commerce_enabled, currency, facet_hints)
values (
  'avkare', 'AvKARE', true, 'USD',
  '["strength","form","therapeutic category","pack size","NDC"]'::jsonb
)
on conflict (site_key) do update set
  commerce_enabled = excluded.commerce_enabled,
  currency = excluded.currency,
  facet_hints = excluded.facet_hints;

insert into public.commerce_catalog (site_key, sku, name, description, category, image_url, product_url, list_price, uom, specs, price_breaks, stock_qty, lead_time_days, min_order_qty, restricted, restriction) values (
  'avkare', 'AV-42806-01', 'Acetaminophen 500 mg Tablets, 100 ct', 'Extra-strength acetaminophen tablets for temporary relief of minor aches, pains, and fever. USP-grade, unit-of-use bottle.', 'Analgesics', '/drafts/images/avkare/rx-tablet.svg', '/drafts/pdp', 4.85, 'bottle', '{"strength":"500 mg","form":"Tablet","therapeutic category":"Analgesic / Antipyretic","pack size":"100 count","NDC":"42806-0100-01"}'::jsonb, '[{"min_qty":24,"unit_price":4.35},{"min_qty":144,"unit_price":3.75}]'::jsonb, 5200, 0, 1, false, null
) on conflict (site_key, sku) do update set name=excluded.name, description=excluded.description, category=excluded.category, image_url=excluded.image_url, product_url=excluded.product_url, list_price=excluded.list_price, specs=excluded.specs, price_breaks=excluded.price_breaks, stock_qty=excluded.stock_qty, lead_time_days=excluded.lead_time_days, restricted=excluded.restricted, restriction=excluded.restriction;

insert into public.commerce_catalog (site_key, sku, name, description, category, image_url, product_url, list_price, uom, specs, price_breaks, stock_qty, lead_time_days, min_order_qty, restricted, restriction) values (
  'avkare', 'AV-52427-15', 'Amoxicillin 500 mg Capsules, 100 ct', 'Broad-spectrum penicillin-class antibiotic capsules indicated for susceptible bacterial infections. AB-rated generic.', 'Anti-Infectives', '/drafts/images/avkare/rx-capsule.svg', '/drafts/pdp', 9.2, 'bottle', '{"strength":"500 mg","form":"Capsule","therapeutic category":"Antibiotic (Penicillin)","pack size":"100 count","NDC":"52427-0281-01"}'::jsonb, '[{"min_qty":24,"unit_price":8.4},{"min_qty":100,"unit_price":7.25}]'::jsonb, 1840, 0, 1, false, null
) on conflict (site_key, sku) do update set name=excluded.name, description=excluded.description, category=excluded.category, image_url=excluded.image_url, product_url=excluded.product_url, list_price=excluded.list_price, specs=excluded.specs, price_breaks=excluded.price_breaks, stock_qty=excluded.stock_qty, lead_time_days=excluded.lead_time_days, restricted=excluded.restricted, restriction=excluded.restriction;

insert into public.commerce_catalog (site_key, sku, name, description, category, image_url, product_url, list_price, uom, specs, price_breaks, stock_qty, lead_time_days, min_order_qty, restricted, restriction) values (
  'avkare', 'AV-42806-33', 'Ibuprofen 800 mg Tablets, 500 ct', 'Prescription-strength NSAID tablets for pain and inflammation. Film-coated, institutional 500-count bottle.', 'Analgesics', '/drafts/images/avkare/rx-tablet.svg', '/drafts/pdp', 12.6, 'bottle', '{"strength":"800 mg","form":"Tablet","therapeutic category":"NSAID / Analgesic","pack size":"500 count","NDC":"42806-0522-05"}'::jsonb, '[{"min_qty":12,"unit_price":11.4},{"min_qty":72,"unit_price":9.95}]'::jsonb, 980, 0, 1, false, null
) on conflict (site_key, sku) do update set name=excluded.name, description=excluded.description, category=excluded.category, image_url=excluded.image_url, product_url=excluded.product_url, list_price=excluded.list_price, specs=excluded.specs, price_breaks=excluded.price_breaks, stock_qty=excluded.stock_qty, lead_time_days=excluded.lead_time_days, restricted=excluded.restricted, restriction=excluded.restriction;

insert into public.commerce_catalog (site_key, sku, name, description, category, image_url, product_url, list_price, uom, specs, price_breaks, stock_qty, lead_time_days, min_order_qty, restricted, restriction) values (
  'avkare', 'AV-16714-08', 'Metformin HCl 500 mg Tablets, 100 ct', 'Oral biguanide antihyperglycemic tablets for the management of type 2 diabetes mellitus. AB-rated generic.', 'Endocrine / Metabolic', '/drafts/images/avkare/rx-tablet.svg', '/drafts/pdp', 6.4, 'bottle', '{"strength":"500 mg","form":"Tablet","therapeutic category":"Antidiabetic (Biguanide)","pack size":"100 count","NDC":"16714-0089-01"}'::jsonb, '[{"min_qty":24,"unit_price":5.8},{"min_qty":144,"unit_price":4.95}]'::jsonb, 3100, 0, 1, false, null
) on conflict (site_key, sku) do update set name=excluded.name, description=excluded.description, category=excluded.category, image_url=excluded.image_url, product_url=excluded.product_url, list_price=excluded.list_price, specs=excluded.specs, price_breaks=excluded.price_breaks, stock_qty=excluded.stock_qty, lead_time_days=excluded.lead_time_days, restricted=excluded.restricted, restriction=excluded.restriction;

insert into public.commerce_catalog (site_key, sku, name, description, category, image_url, product_url, list_price, uom, specs, price_breaks, stock_qty, lead_time_days, min_order_qty, restricted, restriction) values (
  'avkare', 'AV-68180-51', 'Lisinopril 10 mg Tablets, 100 ct', 'ACE inhibitor tablets for hypertension and heart-failure management. Scored, unit-of-use bottle.', 'Cardiovascular', '/drafts/images/avkare/rx-tablet.svg', '/drafts/pdp', 5.75, 'bottle', '{"strength":"10 mg","form":"Tablet","therapeutic category":"Antihypertensive (ACE Inhibitor)","pack size":"100 count","NDC":"68180-0514-01"}'::jsonb, '[{"min_qty":24,"unit_price":5.2},{"min_qty":144,"unit_price":4.45}]'::jsonb, 2650, 0, 1, false, null
) on conflict (site_key, sku) do update set name=excluded.name, description=excluded.description, category=excluded.category, image_url=excluded.image_url, product_url=excluded.product_url, list_price=excluded.list_price, specs=excluded.specs, price_breaks=excluded.price_breaks, stock_qty=excluded.stock_qty, lead_time_days=excluded.lead_time_days, restricted=excluded.restricted, restriction=excluded.restriction;

insert into public.commerce_catalog (site_key, sku, name, description, category, image_url, product_url, list_price, uom, specs, price_breaks, stock_qty, lead_time_days, min_order_qty, restricted, restriction) values (
  'avkare', 'AV-43547-32', 'Atorvastatin Calcium 20 mg Tablets, 90 ct', 'HMG-CoA reductase inhibitor (statin) tablets for the reduction of LDL cholesterol. Film-coated.', 'Cardiovascular', '/drafts/images/avkare/rx-tablet.svg', '/drafts/pdp', 8.9, 'bottle', '{"strength":"20 mg","form":"Tablet","therapeutic category":"Lipid-Lowering (Statin)","pack size":"90 count","NDC":"43547-0322-09"}'::jsonb, '[{"min_qty":24,"unit_price":8.05},{"min_qty":100,"unit_price":6.95}]'::jsonb, 1420, 0, 1, false, null
) on conflict (site_key, sku) do update set name=excluded.name, description=excluded.description, category=excluded.category, image_url=excluded.image_url, product_url=excluded.product_url, list_price=excluded.list_price, specs=excluded.specs, price_breaks=excluded.price_breaks, stock_qty=excluded.stock_qty, lead_time_days=excluded.lead_time_days, restricted=excluded.restricted, restriction=excluded.restriction;

insert into public.commerce_catalog (site_key, sku, name, description, category, image_url, product_url, list_price, uom, specs, price_breaks, stock_qty, lead_time_days, min_order_qty, restricted, restriction) values (
  'avkare', 'AV-68382-06', 'Omeprazole 20 mg Delayed-Release Capsules, 100 ct', 'Proton-pump inhibitor delayed-release capsules for GERD and acid-related disorders. Enteric-coated pellets.', 'Gastrointestinal', '/drafts/images/avkare/rx-capsule.svg', '/drafts/pdp', 10.3, 'bottle', '{"strength":"20 mg","form":"DR Capsule","therapeutic category":"Proton-Pump Inhibitor","pack size":"100 count","NDC":"68382-0512-01"}'::jsonb, '[{"min_qty":24,"unit_price":9.35},{"min_qty":100,"unit_price":8.1}]'::jsonb, 1760, 0, 1, false, null
) on conflict (site_key, sku) do update set name=excluded.name, description=excluded.description, category=excluded.category, image_url=excluded.image_url, product_url=excluded.product_url, list_price=excluded.list_price, specs=excluded.specs, price_breaks=excluded.price_breaks, stock_qty=excluded.stock_qty, lead_time_days=excluded.lead_time_days, restricted=excluded.restricted, restriction=excluded.restriction;

insert into public.commerce_catalog (site_key, sku, name, description, category, image_url, product_url, list_price, uom, specs, price_breaks, stock_qty, lead_time_days, min_order_qty, restricted, restriction) values (
  'avkare', 'AV-31722-54', 'Sertraline HCl 50 mg Tablets, 100 ct', 'SSRI antidepressant tablets indicated for major depressive disorder, OCD, and anxiety disorders. Film-coated, scored.', 'CNS / Mental Health', '/drafts/images/avkare/rx-tablet.svg', '/drafts/pdp', 7.15, 'bottle', '{"strength":"50 mg","form":"Tablet","therapeutic category":"Antidepressant (SSRI)","pack size":"100 count","NDC":"31722-0542-01"}'::jsonb, '[{"min_qty":24,"unit_price":6.5},{"min_qty":144,"unit_price":5.55}]'::jsonb, 1290, 0, 1, false, null
) on conflict (site_key, sku) do update set name=excluded.name, description=excluded.description, category=excluded.category, image_url=excluded.image_url, product_url=excluded.product_url, list_price=excluded.list_price, specs=excluded.specs, price_breaks=excluded.price_breaks, stock_qty=excluded.stock_qty, lead_time_days=excluded.lead_time_days, restricted=excluded.restricted, restriction=excluded.restriction;

insert into public.commerce_catalog (site_key, sku, name, description, category, image_url, product_url, list_price, uom, specs, price_breaks, stock_qty, lead_time_days, min_order_qty, restricted, restriction) values (
  'avkare', 'AV-00093-72', 'Albuterol Sulfate Inhalation Solution 0.083%, 25 x 3 mL', 'Beta-2 agonist bronchodilator unit-dose vials for nebulization. Preservative-free, 25-vial institutional carton.', 'Respiratory', '/drafts/images/avkare/rx-vial.svg', '/drafts/pdp', 14.75, 'carton', '{"strength":"0.083% (2.5 mg/3 mL)","form":"Inhalation Solution","therapeutic category":"Bronchodilator (Beta-2 Agonist)","pack size":"25 unit-dose vials","NDC":"00093-7203-25"}'::jsonb, '[{"min_qty":12,"unit_price":13.4},{"min_qty":48,"unit_price":11.6}]'::jsonb, 640, 3, 1, false, null
) on conflict (site_key, sku) do update set name=excluded.name, description=excluded.description, category=excluded.category, image_url=excluded.image_url, product_url=excluded.product_url, list_price=excluded.list_price, specs=excluded.specs, price_breaks=excluded.price_breaks, stock_qty=excluded.stock_qty, lead_time_days=excluded.lead_time_days, restricted=excluded.restricted, restriction=excluded.restriction;

insert into public.commerce_catalog (site_key, sku, name, description, category, image_url, product_url, list_price, uom, specs, price_breaks, stock_qty, lead_time_days, min_order_qty, restricted, restriction) values (
  'avkare', 'AV-42806-77', 'Prednisone 20 mg Tablets, 100 ct', 'Corticosteroid tablets for a broad range of inflammatory and immune conditions. Scored, unit-of-use bottle.', 'Endocrine / Metabolic', '/drafts/images/avkare/rx-tablet.svg', '/drafts/pdp', 6.95, 'bottle', '{"strength":"20 mg","form":"Tablet","therapeutic category":"Corticosteroid","pack size":"100 count","NDC":"42806-0774-01"}'::jsonb, '[{"min_qty":24,"unit_price":6.3},{"min_qty":144,"unit_price":5.4}]'::jsonb, 2010, 0, 1, false, null
) on conflict (site_key, sku) do update set name=excluded.name, description=excluded.description, category=excluded.category, image_url=excluded.image_url, product_url=excluded.product_url, list_price=excluded.list_price, specs=excluded.specs, price_breaks=excluded.price_breaks, stock_qty=excluded.stock_qty, lead_time_days=excluded.lead_time_days, restricted=excluded.restricted, restriction=excluded.restriction;

insert into public.commerce_catalog (site_key, sku, name, description, category, image_url, product_url, list_price, uom, specs, price_breaks, stock_qty, lead_time_days, min_order_qty, restricted, restriction) values (
  'avkare', 'AV-00591-38', 'Alprazolam 0.5 mg Tablets, 100 ct (CIV)', 'Benzodiazepine tablets for anxiety disorders. Schedule IV controlled substance — requires a valid DEA account and controlled-substance entitlement.', 'CNS / Mental Health', '/drafts/images/avkare/rx-tablet.svg', '/drafts/pdp', 8.6, 'bottle', '{"strength":"0.5 mg","form":"Tablet","therapeutic category":"Anxiolytic (Benzodiazepine)","pack size":"100 count","NDC":"00591-0383-01","DEA schedule":"CIV"}'::jsonb, '[{"min_qty":24,"unit_price":7.8}]'::jsonb, 220, 5, 1, true, 'Controlled substance — requires DEA account + entitlement'
) on conflict (site_key, sku) do update set name=excluded.name, description=excluded.description, category=excluded.category, image_url=excluded.image_url, product_url=excluded.product_url, list_price=excluded.list_price, specs=excluded.specs, price_breaks=excluded.price_breaks, stock_qty=excluded.stock_qty, lead_time_days=excluded.lead_time_days, restricted=excluded.restricted, restriction=excluded.restriction;

insert into public.commerce_catalog (site_key, sku, name, description, category, image_url, product_url, list_price, uom, specs, price_breaks, stock_qty, lead_time_days, min_order_qty, restricted, restriction) values (
  'avkare', 'AV-68180-99', 'Losartan Potassium 50 mg Tablets, 90 ct', 'Angiotensin II receptor blocker (ARB) tablets for hypertension and diabetic nephropathy. Film-coated.', 'Cardiovascular', '/drafts/images/avkare/rx-tablet.svg', '/drafts/pdp', 7.4, 'bottle', '{"strength":"50 mg","form":"Tablet","therapeutic category":"Antihypertensive (ARB)","pack size":"90 count","NDC":"68180-0992-09"}'::jsonb, '[{"min_qty":24,"unit_price":6.7},{"min_qty":144,"unit_price":5.75}]'::jsonb, 1880, 0, 1, false, null
) on conflict (site_key, sku) do update set name=excluded.name, description=excluded.description, category=excluded.category, image_url=excluded.image_url, product_url=excluded.product_url, list_price=excluded.list_price, specs=excluded.specs, price_breaks=excluded.price_breaks, stock_qty=excluded.stock_qty, lead_time_days=excluded.lead_time_days, restricted=excluded.restricted, restriction=excluded.restriction;

